### PR TITLE
Merge: Added Player Statistic Tables

### PR DESCRIPTION
**Pull request by 18PatZ**
Added Player Statistic Tables. Set stats in tables on window.onload. Set health limit at 0. Set health stat in table to be in sync with health of players.
Sorry for so many commits XD
If you want you can check new version at http://18patz.github.io/spaceshiptanks/ before merging.

### CODE REVIEW

**Comment by 18praveenb** [comment]
There should be only 1 table. P1 & P2 will have multiple units so the table will just show the stats of the unit that the mouse is hovering over.

**Comment by 18PatZ** [comment]
Oh okay
The tables gonna be empty when u don't hover?

**Comment by 18PatZ** [comment]
It is easier to be able to see player stats at all times right?

**Comment by 18praveenb** [comment]
yeah tables will be empty without hover because they won't know which unit stats to show.

**Comment by 18praveenb** [comment]
I'll accept this and modify it to work on hover

**Comment by 18praveenb** [comment]
actually might keep 2 stat tables and always showing stats
this might be cooler as a real time game instead of turn based

**Comment by 18PatZ** [comment]
Maybe another table underneath for hover?

**Comment by 18praveenb** [comment]
ok so what I've done is
I have created a new branch
which is just a 1v1 spaceship game & will use the 2 tables to show stats.

The gh-pages branch should have only a hover table and no player tables (I'll edit that later as I'm going to be working on the new branch for a week or so)

**Comment by 18PatZ** [comment]
Okay so the 1v1 branch does not have units?
Is there some way to view the html file of a new branch through GitHub?

**Comment by 18PatZ** [comment]
How to merge YOUR branch into MY repo?

**Comment by 18praveenb** [comment]
create a new pull request.

set the base fork to 18patz/spaceshiptanks with the base realtime (create a new branch so you don't lose the gh-pages branch)

set the head fork to 18praveenb/spaceshpanks with the compare: realtime

**Pull request merged**
